### ISSUE TITLE
Feature request: Support german and english language

### ISSUE THREAD

**Issue by merlinuwe** [karlsbeard/obsidian-univer#31]
### Problem

I cannot read chinese language.

### Solution

Translation seem to be supported by univer.

### Additional details

Thank you very much for your great plugin!

**Comment by karlsbeard** [comment]
glad to receive ur issue. I will feat this function as soon as possible. Good day.

**Comment by karlsbeard** [comment]
> ### Problem
> I cannot read chinese language.
> 
> ### Solution
> Translation seem to be supported by univer.
> 
> ### Additional details
> Thank you very much for your great plugin!

the plugin has update, now u can use the plugin setting option to change the language to Chinese or English, now the default language is English. Thanks for ur issue again. Good day to u.
