### ISSUE TITLE
The formula bar does not display content upon first entering the table

### ISSUE THREAD

**Issue by DR-Univer** [karlsbeard/obsidian-univer#33]
### Describe the bug

![image](https://github.com/karlsbeard/obsidian-univer/assets/68851825/278de3bf-5000-45b0-ba32-fbfe317396a9)

The formula bar does not display content upon first entering the table

### Steps to reproduce

Upon first entering the table, clicking to switch cells with the mouse does not display content in the formula bar. One must manually click on the formula bar before entering data for it to behave normally.

### Expected behavior

formula bar show content

### Are you using the mobile app?

Yes

### Obsidian debug info

no content

**Comment by karlsbeard** [comment]
This is the feature of Univer. You can view the following the code:
https://github.com/dream-num/univer/blob/7d27f1178f681e4b912326627b5e44dd77085048/packages/ui/src/controllers/ui/ui-desktop.controller.tsx#L48
