### ISSUE TITLE
Zoom tool bar show underline

### ISSUE THREAD

**Issue by DR-Univer** [karlsbeard/obsidian-univer#36]
### Describe the bug

![image](https://github.com/karlsbeard/obsidian-univer/assets/68851825/a81fe819-d96f-4bc4-be2a-7fd197437a80)

### Steps to reproduce

It's very obvious

### Expected behavior

It's very obvious

### Are you using the mobile app?

Yes

### Obsidian debug info

It's very obvious

**Comment by karlsbeard** [comment]
Thanks for your bug issue. The bug has been fixed and will be found in the next version.
