### ISSUE TITLE
All panel text is wrong

### ISSUE THREAD

**Issue by DR-Univer** [karlsbeard/obsidian-univer#38]
### Describe the bug

![image](https://github.com/karlsbeard/obsidian-univer/assets/68851825/fd054b2f-ff7b-43e7-884e-9808d9771865)

### Steps to reproduce

very obvious question

### Expected behavior

very obvious question

### Are you using the mobile app?

Yes

### Obsidian debug info

very obvious question

**Comment by karlsbeard** [comment]
Thanks for your issue, I have fix this.
